### ISSUE TITLE
Difficulty with debugging

### ISSUE THREAD

**Issue by alexhallam** [LaunchPlatform/beancount-black#9]
I have the following error.

I am not able to determine what the source of error is

```
INFO:beancount_black.main:Processing file ledger.bean
Traceback (most recent call last):
  File "/home/user/.local/bin/bean-black", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/beancount_black/main.py", line 49, in main
    formatter.format(tree, output_file)
  File "/home/user/.local/lib/python3.9/site-packages/beancount_black/formatter.py", line 558, in format
    self.calculate_column_widths(tree)
  File "/home/user/.local/lib/python3.9/site-packages/beancount_black/formatter.py", line 550, in calculate_column_widths
    width = len(self.format_number(amount.children[0]))
  File "/home/user/.local/lib/python3.9/site-packages/beancount_black/formatter.py", line 210, in format_number
    value = token.value.replace(",", "")
AttributeError: 'Tree' object has no attribute 'value'
```

**Comment by kaiwei** [comment]
I have the same error with a valid bean-check verified file as well.

**Comment by fangpenlin** [comment]
Hi there, thanks for reporting this issue. I am currently overwhelmed by other stuff, will look into this later when I have more spare time

**Comment by fangpenlin** [comment]
@alexhallam @kaiwei sorry for long waiting, now the new logging level option has been added

https://github.com/LaunchPlatform/beancount-black#debug

that should make it much easier to debug if there's anything stop the formatter from formatting

**Comment by fangpenlin** [comment]
the `AttributeError: 'Tree' object has no attribute 'value'` from `format_number` bug has been fixed in the latest version as well, by the way
